### PR TITLE
Prefix the install path to the circleci binary

### PR DESCRIPTION
**Pull request by Miyurz**
- [x] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x] I have checked for similar issues and haven't found anything relevant.
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)

**Here are some helpful tips you can follow when submitting a pull request:**

1. Fork [the repository](https://github.com/CircleCI-Public/circleci-cli) and create your branch from `master`.
2. Run `make build` in the repository root.
3. If you've fixed a bug or added code that should be tested, add tests!
4. Ensure the test suite passes (`make test`).
5. The `--debug` flag is often helpful for debugging HTTP client requests and responses.
6. Format your code with [gofmt](https://golang.org/cmd/gofmt/).
7. Make sure your code lints (`make lint`). Note: This requires Docker to run inside a local job.

**If you have any questions, feel free to ping us at @CircleCI-Public/x-team.**

### CODE REVIEW

**Comment by Miyurz** [comment]
The failure is n't related to my change. It's failing in the "deploy-test" while installing the goreleaser

**Comment by dnephin** [comment]
https://github.com/CircleCI-Public/circleci-cli/pull/357/commits/c5b2cd499937bf19069ae49666c861e4bbc1eadc has a fix for the deploy-test step.

**Comment by Miyurz** [comment]
@dnephin  I am not able to re-run this build even after merging the latest of master with this change. Can you help me trigger this build ?

**Comment by corinnesollows** [comment]
This does not seem to pass the checks and due to the age of this PR, I will be closing it out. Feel free to make a fresh PR at any time. :)

**Pull request closed without merging**
