### PR TITLE
Document packr2 requirement

### PR DESCRIPTION
**Pull request by eric-hu**
Documenting something I fumbled with while trying to make a small PR earlier today.

- [x] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x] I have checked for similar issues and haven't found anything relevant.
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)

### CODE REVIEW

**Comment by zzak** [comment]
I would personally rather install [a release](https://github.com/gobuffalo/packr/releases/tag/v2.0.0-rc.14), even if it's in RC. The binary is only 3MB and using `go get` can take a very long time due to the number of dependencies they have -- also there's a chance it messes with your `go.mod` file :man_facepalming:

**Comment by eric-hu** [comment]
Updated to point to the binary release. It threw me off that the `packr2` folder in that repo has both library and binary install instructions. Even the binary instructions in there use `go get`, which fetches a bunch of libraries as you pointed out.

**Comment by zzak** [comment]
@eric-hu Also [2.0.0](https://github.com/gobuffalo/packr/releases/tag/v2.0.0) was finally released, so we can just use that.

**Comment by eric-hu** [comment]
Yep, that's what the instructions are now pointing to. I only included macOS instructions since I wasn't sure what a good directory would be for unzipping to on Linux (or if the `tar` flags might be slightly different).

**Comment by eric-hu** [comment]
Came here to close this after `make dev` took care of this problem. Thanks for taking care of this @zzak !

**Pull request closed without merging**
