### PR TITLE
--env contains commas get unexpectedly split

### PR DESCRIPTION
**Pull request by Kuniwak**
`StringSliceP` splits an argument by commas, so parsing results get corrupt if the argument contains comma.
So we should use `StringArrayP` instead of `StringSliceP`.

* StringSliceP: `--ss a,b --ss c`   →  `["a", "b", "c"]` 😕 
* StringArrayP: `--ss a,b --ss c`  →  `["a,b", "c"]` 😄 

Arguments contain commas are frequently present when you use private images on Google Container Registry (GCR).
GCR can use a password encoded by JSON (called as JSON key file [^1]) for native basic auth [^2] of Docker.
And only we can do without embedding the password into .circleci/config.yml is specifying the password via --env.

[^1]: https://cloud.google.com/container-registry/docs/advanced-authentication#json-key
[^2]: https://docs.docker.com/registry/deploying/#native-basic-auth

Related #389 

---

- [x] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x] I have checked for similar issues and haven't found anything relevant.
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)

### CODE REVIEW

**Comment by Kuniwak** [comment]
**FYI**: We can avoid this problem using `--` before `--env`. For example:

```console
$ circleci local execute --job build -- --env FOO=BAR,BAZ
```

**Comment by Kuniwak** [comment]
@aengelberg

Hi, how do I do to request to review this pull request?  (I mentioned you because of you seems recent active committer)

**Comment by Kuniwak** [comment]
@aengelberg @gmemstr @polymeris @sulami

Hi, we are facing the problem in our CircleCI Enterprise server, so we are strongly hoping to fix it as soon as possible...

**Review by aengelberg — APPROVED** [review]
Thanks for the PR, and sorry for the delay on reviewing. This seems like a good change. It potentially affects existing users if they were utilizing the comma splitting behavior intentionally, but in that case it's easy to switch to passing in multiple `--env` flags.

**Pull request merged**
