### PR TITLE
ci: use golangci-lint docker image directly

### PR DESCRIPTION
**Pull request by wyardley**
# Checklist

=========

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have checked for similar issues and haven't found anything relevant.
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)
- [x] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).

## Changes

=======
- Directly use golangci-lint in Docker in CI
- Remove unused lint scripts and Makefile targets
- Update Makefile to call golangci-lint directly for lint target (for local use)
- Update golangci-lint version from 1.35 to 1.46
- Remove golangmetalinter config, which was seemingly ignored, and add a config for golangci-lint
- Resolve one new lint warning from a test case
- Update formatting on files that were not properly formatted

## Rationale
=========
As noted in #688, `go fmt` wasn't being applied / linted in CI, and using Docker to directly run this would be simpler / more efficient.

Also, the version of golangci-lint used was old, and the only config seems to have been the (ignored?, and deprecated) `.gometalinter.json`. I took what seems to have been the intent of that config, commented out (for now) a few that are failing (for further review).

## Considerations

==============
I chose the linters that were enabled implicitly by the default config, as well as the (working) ones that were in the original gometalinter configuration. May be good to review the findings from the commented out linters or consider adding some additional ones. I left `goconst` disabled for tests, because there are a lot of repetitive strings there that are getting flagged.

I figured that this is a good incremental step that can be built on, while still reducing the amount of change to the code base in this PR.

## Screenshots

============

<h4>Before</h4>
Image or [gif](https://giphy.com/apps/giphycapture)

<h4>After</h4>
Image or gif where change can be clearly seen

## **Here are some helpful tips you can follow when submitting a pull request:**

1. Fork [the repository](https://github.com/CircleCI-Public/circleci-cli) and create your branch from `master`.
2. Run `make build` in the repository root.
3. If you've fixed a bug or added code that should be tested, add tests!
4. Ensure the test suite passes (`make test`).
5. The `--debug` flag is often helpful for debugging HTTP client requests and responses.
6. Format your code with [gofmt](https://golang.org/cmd/gofmt/).
7. Make sure your code lints (`make lint`). Note: This requires Docker to run inside a local job.

### CODE REVIEW

**Comment by wyardley** [comment]
note: the codecov stuff that's failing is due to things with formatting-only changes, I think.

@KyleTryon any chance you could poke someone on the team that owns this?

**Comment by wyardley** [comment]
@joeyorlando any chance you could take a look or have someone take a look?

**Comment by wyardley** [comment]
@rykimcircle are you able to take a look at this one?

**Comment by wyardley** [comment]
@davidmdm would you have time to take a look at this?

(btw, also note warning w/ go 1.18:)
```
WARN [linters context] structcheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649. 
```

**Review by jtmcg — APPROVED** [review]

**Review by li3n3 — APPROVED** [review]
Thank you for the thoughtful PR, @wyardley!

Reviewed this with @jtmcg and verified locally. We can find no historical reasons for maintaining `.gometalinter.json` as an alternative (and its most recent changes were four years ago, anyway), so we're happy to accept.

**Pull request merged**
