### PR TITLE
changed the `context list` table

### PR DESCRIPTION
**Pull request by JulesFaucherre**
# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have checked for similar issues and haven't found anything relevant.
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)
- [x] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/main/CONTRIBUTING.md).

### Internal Checklist
- [x] I am requesting a review from my own team as well as the owning team
- [x] I have a plan in place for the monitoring of the changes that I am making (this can include new monitors, logs to be aware of, etc...)

## Changes

- Adding few product changes discussed in [the ticket](https://circleci.atlassian.net/browse/DEVEX-1216).

## Rationale

N/A.

## Considerations

N/A.

##### `circleci context list`
<h4>Before</h4>
Capture d’écran 2024-02-22 à 10 23 40

<h4>After</h4>

Capture d’écran 2024-02-28 à 16 55 09

##### `circleci context list`

<h4>Before</h4>

Capture d’écran 2024-02-22 à 10 38 21

<h4>After</h4>

Removed the slug from the message.
Capture d’écran 2024-02-28 à 16 56 43

### CODE REVIEW

**Comment by jvincent42** [comment]
What do you think of keeping the slug in the confirmation question ? Since we are using org-id now, it would be a nice indication that you are on the right organisation.

**Comment by JulesFaucherre** [comment]
Yeah but it doesn't really make sense as for standalone you'd get `circleci/<strange-id>` one thing we can do is give the project name.

**Comment by jvincent42** [comment]
Isn't it possible to get the organisation name ?

**Comment by JulesFaucherre** [comment]
Oh sure, I meant the org name! Making the change.

**Comment by JulesFaucherre** [comment]
There is now the org name:
Capture d’écran 2024-03-04 à 09 46 49

**Review by jvincent42 — APPROVED** [review]

**Pull request merged**
