### PR TITLE
Hack week help menu

### PR DESCRIPTION
**Pull request by corinnesollows**
# Checklist

=========

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have checked for similar issues and haven't found anything relevant.
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)
- [x] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).

## Changes

=======

- Beautified Cobra Command Help menu by overwriting their default help menu

## Rationale

=========

Implementing changes that were made during last hack week

## Considerations

==============

Helping make our CLI look more professional

## Screenshots

============

<h4>Before</h4>
Screen Shot 2022-09-20 at 3 03 38 PM

<h4>After</h4>
Light Mode:
Screen Shot 2022-09-20 at 2 50 14 PM

Dark Mode:
Screen Shot 2022-09-20 at 2 50 29 PM

### CODE REVIEW

**Review by am-bui — APPROVED** [review]
Clean and pretty!

**Comment by mjgiarlo** [comment]
Hi! Love these CLI changes.

Naïve question: how does one switch between dark and light modes?

**Comment by adam-alula** [comment]
I'm with @mjgiarlo wondering how I utilize light mode. I cannot read the help menu anymore in my terminal which uses a light theme. The border also wraps poorly if a terminal is only so wide.

**Comment by mjgiarlo** [comment]
@adam-alula 💬 
> I'm with @mjgiarlo wondering how I utilize light mode. I cannot read the help menu anymore in my terminal which uses a light theme. The border also wraps poorly if a terminal is only so wide.

Yes, that is the same boat I'm in. In the meantime, you can prefix `TESTING=true` to the CLI command to get back the old menu.

**Comment by mjgiarlo** [comment]
@adam-alula As best I can tell, this is handled entirely automagically via the `termenv` library---I can't find any switches, environment variables, or configuration to vary this as a CLI user. You can see termenv's support for various terminals here: https://github.com/muesli/termenv#optional-feature-support (As a `tmux` user myself, this is a bit of a bummer, but `TESTING=true` is good enough for me.)

**Comment by adam-alula** [comment]
@mjgiarlo setting `TESTING` works for now. I will create an alias and cross my fingers until I have to address this again. Thank you for the insight into the problem!

**Comment by mjgiarlo** [comment]
@adam-alula While spelunking in the [`termenv` library](https://github.com/muesli/termenv/blob/c2e45bfa2bd18c9d6bd2a85371b4cf24168350b8/termenv_unix.go#L68-L110), I discovered the `COLORFGBG` environment variable which it can use to determine whether the terminal has a dark or light background. My terminal doesn't set it by default, so I figured why not try it?

So to "force" light mode:

```shell
$ COLORFGBG="0;15" circleci help
```

or dark mode:

```shell
$ COLORFGBG="15;0" circleci help
```

Works for me, anyway.

**Pull request merged**
